# Generated by Django 3.1 on 2020-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0002_orderitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('serve', 'Serve'), ('cancel', 'Cancel')], default='pending', max_length=15),
        ),
    ]
