# Generated by Django 3.1 on 2020-08-25 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Please enter correct phone number.', regex='\\d{10,10}$')])),
                ('is_on_table', models.BooleanField(default=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('token', models.CharField(default=0, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('on_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.table')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
