# Generated by Django 3.1 on 2020-08-25 12:20

import api.order.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('order_item', '0001_initial'),
        ('payment', '0001_initial'),
        ('coupon', '0001_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='online', max_length=10)),
                ('invoice_no', models.CharField(default=api.order.models.increment_invoice_number, max_length=500, unique=True)),
                ('otp', models.IntegerField(default=api.order.models.generateOTP)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.coupon')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('items', models.ManyToManyField(to='order_item.OrderItem')),
                ('payment', models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
